<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Bibliotheque;

class BibliothequeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'titre' => 'Guide Complet du Développement Web Fullstack',
                'auteur' => 'Alexandre Martin',
                'description' => 'Maîtrisez les fondamentaux du développement frontend et backend : HTML5, CSS3, JavaScript moderne, PHP et bases de données relationnelles.',
                'categorie' => 'informatique',
                'fichier_pdf' => 'bibliotheque/pdfs/7lE0UO4fi0O9W3oonMworiQP9T0HotJyXbydAP8f.pdf',
                'cover_image' => 'bibliotheque/covers/4BAUqItIrpzdS4qDOThoVA9trsnwYBmfFiZUQfFx.jpg',
                'nombre_pages' => 245,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Entrepreneuriat Pratique : De l\'Idée au Premier Client',
                'auteur' => 'Christian Ngan',
                'description' => 'Un manuel pas-à-pas pour structurer son business model, valider son marché en Afrique et lancer une entreprise rentable avec peu de capital initial.',
                'categorie' => 'entrepreneuriat',
                'fichier_pdf' => 'bibliotheque/pdfs/8Em39Lut9db2Q11cJRaSOORYB8Lq1kAMixmOnti1.pdf',
                'cover_image' => 'bibliotheque/covers/8lax6vUZ3TcDMgce4q6kGLobDrmoh7Y3QhEb19Tx.jpg',
                'nombre_pages' => 180,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Stratégies de Marketing Digital & Réseaux Sociaux',
                'auteur' => 'Sophie Laurent',
                'description' => 'Développez votre visibilité en ligne : acquisition client, publicité Facebook Ads, création de contenu viral et optimisation du taux de conversion.',
                'categorie' => 'marketing',
                'fichier_pdf' => 'bibliotheque/pdfs/92GUB4av9nRfqT3YKHkKl0F8emM3uETZ5BePxHze.pdf',
                'cover_image' => 'bibliotheque/covers/AmPziVKYBwgod89oQbL4sqj9M4FIBnPxyizVmG4n.jpg',
                'nombre_pages' => 210,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Comptabilité Générale et Analyse Financière SYSCOHADA',
                'auteur' => 'Jean-Paul Kamga',
                'description' => 'Comprendre les mécanismes comptables, le bilan, le compte de résultat et la gestion de trésorerie selon le système comptable OHADA.',
                'categorie' => 'comptabilite',
                'fichier_pdf' => 'bibliotheque/pdfs/9DRf0LUbGKZTbP7YpZFHBFhU0rsKZ2EaeONcZaWL.pdf',
                'cover_image' => 'bibliotheque/covers/B4cFrGvWJEBihhNxPsZUtuaKSjG34U4ZXtqKWzIe.jpg',
                'nombre_pages' => 320,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Management et Gestion de Projet Agile',
                'auteur' => 'Marc Dubois',
                'description' => 'Méthodologies Scrum et Kanban pour planifier, exécuter et livrer des projets dans les délais impartis avec une équipe motivée.',
                'categorie' => 'gestion',
                'fichier_pdf' => 'bibliotheque/pdfs/ArlupYyOL1zmCtBS73PWM2pXoHiN5zWnw6GnVFY5.pdf',
                'cover_image' => 'bibliotheque/covers/CTkECcE2Mo0YPFH8PKMAWYNnWdJmemV9qupMqjzP.jpg',
                'nombre_pages' => 195,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Droit des Affaires et Pratique des Contrats Commerciaux',
                'auteur' => 'Me Alain Fotso',
                'description' => 'Guide juridique essentiel pour sécuriser vos partenariats, rédiger des contrats de prestation solides et prévenir les litiges commerciaux.',
                'categorie' => 'droit',
                'fichier_pdf' => 'bibliotheque/pdfs/D7z3JpSocfLcvEZ26Z8MVNWkmJHMOuZKrcfJQxvH.pdf',
                'cover_image' => 'bibliotheque/covers/Cdz4uE6NaRY8H4G7zADCPLjPghbFAydgW5YMRIyj.jpg',
                'nombre_pages' => 260,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Productivité et Leadership : Les Clés de l\'Excellence',
                'auteur' => 'David Kouam',
                'description' => 'Techniques avancées de gestion du temps, prise de décision sous pression et développement du leadership personnel et professionnel.',
                'categorie' => 'developpement_personnel',
                'fichier_pdf' => 'bibliotheque/pdfs/HSfW4Upowf9F4VlDF3vpVLKIfIxuHFwlQrJXWo3A.pdf',
                'cover_image' => 'bibliotheque/covers/Fkjlb0YFEF8oRFa0ormdJgI6pjaiMVZ2I7gaOkqv.jpg',
                'nombre_pages' => 175,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Commerce International et Négociation Commerciale',
                'auteur' => 'Claire Mendy',
                'description' => 'Techniques de prospection B2B, négociation d\'accords commerciaux et logistique d\'import-export pour maximiser vos marges.',
                'categorie' => 'commerce',
                'fichier_pdf' => 'bibliotheque/pdfs/KDmIalOEKEauq2DK0oMQCmxA41qVRsBH51byu7ve.pdf',
                'cover_image' => 'bibliotheque/covers/GsRPRUzUPddjwWea7UpqpjPbPV6nEGkXghexyCf5.jpg',
                'nombre_pages' => 230,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Architecture Réseau et Sécurité des Systèmes d\'Information',
                'auteur' => 'Patrick Tsafack',
                'description' => 'Fondamentaux des réseaux TCP/IP, configuration des routeurs et switchs, sécurité périmétrique et prévention des cyberattaques.',
                'categorie' => 'informatique',
                'fichier_pdf' => 'bibliotheque/pdfs/MXBV0yfSkOtESomXzas8CpuHEmDSNho8sbk02XzL.pdf',
                'cover_image' => 'bibliotheque/covers/HF7r0l2sgoUeL7uofpono3GCEwBKgl5u2nU3xnWN.jpg',
                'nombre_pages' => 310,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Anglais Professionnel des Affaires & Pitching',
                'auteur' => 'Sarah Johnson',
                'description' => 'Vocabulaire clé, formules de politesse pour e-mails professionnels, et préparation aux présentations et entretiens internationaux en anglais.',
                'categorie' => 'langues',
                'fichier_pdf' => 'bibliotheque/pdfs/OtKHUOBbJGhI6zVm76l35U2D54M4s7cMwjW4vJ8I.pdf',
                'cover_image' => 'bibliotheque/covers/JtheETYd7I38fBedrA8b3DjX7tntWmGLrtqiyUOw.jpg',
                'nombre_pages' => 160,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Bureautique Avancée : Excel Expert pour Gestionnaires',
                'auteur' => 'Éric Noubissi',
                'description' => 'Formules complexes, tableaux croisés dynamiques, graphiques d\'aide à la décision et automatisation avec macros Excel pour booster votre efficacité.',
                'categorie' => 'informatique',
                'fichier_pdf' => 'bibliotheque/pdfs/P41Lw4t7QUxy2qgfd8jZEnyVWAPXaEJvVno705v9.pdf',
                'cover_image' => 'bibliotheque/covers/KXYgNMw7oIS7gG1GIwapRyQlHyiIPFg3Qg5Ki63U.jpg',
                'nombre_pages' => 280,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Création d\'Applications Mobiles Modernes',
                'auteur' => 'Brice Manga',
                'description' => 'Conception d\'interfaces réactives, gestion d\'état et déploiement d\'applications performantes pour iOS et Android.',
                'categorie' => 'informatique',
                'fichier_pdf' => 'bibliotheque/pdfs/PavWSOe8l7LZDuo5u77FF0ln2dRhcSFkqBp1N6Sh.pdf',
                'cover_image' => 'bibliotheque/covers/MFmGxvBsZNv1XmclcN8kl77FAkoFymtgBDA0eUON.jpg',
                'nombre_pages' => 290,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Gestion des Ressources Humaines & Recrutement Élite',
                'auteur' => 'Hélène Moukoko',
                'description' => 'Attirer les meilleurs talents, mener des entretiens d\'embauche efficaces, évaluer les compétences et fidéliser les collaborateurs.',
                'categorie' => 'gestion',
                'fichier_pdf' => 'bibliotheque/pdfs/PlY2V1WePUcAq2wm4luMj1OuyVLPhLvqf6jhmT73.pdf',
                'cover_image' => 'bibliotheque/covers/OXwtd4ZbbgER40KwcLiBbdvErRWncXN3LOOHnqmi.jpg',
                'nombre_pages' => 205,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Le Guide du Copywriting & Vente Persuasive',
                'auteur' => 'Julien Bernard',
                'description' => 'L\'art d\'écrire des textes qui vendent : pages de capture, e-mails de vente et accroches percutantes pour convertir vos prospects.',
                'categorie' => 'marketing',
                'fichier_pdf' => 'bibliotheque/pdfs/QoyPg1OykEyukcEXKvX1ANAHFxefXXsWOIbtgr8m.pdf',
                'cover_image' => 'bibliotheque/covers/QJfKBuUb4lijBgnw9pIqNrHGgQtWKW9blS7YrVxr.jpg',
                'nombre_pages' => 150,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Finance d\'Entreprise et Plan de Financement',
                'auteur' => 'Gérard Biya',
                'description' => 'Calcul de rentabilité, besoin en fonds de roulement (BFR), recherche de financements et relations avec les banques et investisseurs.',
                'categorie' => 'comptabilite',
                'fichier_pdf' => 'bibliotheque/pdfs/UTd3g12KxsARgitnxEWANKS9RMOqqxlu8jIO9enp.pdf',
                'cover_image' => 'bibliotheque/covers/Sijh7xjq9sDgfftoarjYHMSn6Azo4loZERhSY5wv.jpg',
                'nombre_pages' => 275,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Design Graphique et Identité Visuelle de Marque',
                'auteur' => 'Nathalie Eto',
                'description' => 'Création de logos percutants, chartes graphiques professionnelles, typographie et communication visuelle adaptée aux supports modernes.',
                'categorie' => 'autre',
                'fichier_pdf' => 'bibliotheque/pdfs/WVDsNUHWtLtju90whyrQo8pfSDVzoOLVW423tXeV.pdf',
                'cover_image' => 'bibliotheque/covers/TAURuvKvQOZ03HJJPVW7hvw2pwb4boAKcJEqtwtb.png',
                'nombre_pages' => 190,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Data Science & Analyse de Données pour Décideurs',
                'auteur' => 'Dr. Paul Mbarga',
                'description' => 'Introduction aux statistiques appliquées, dashboards interactifs et exploitation des données pour piloter la performance de l\'entreprise.',
                'categorie' => 'sciences',
                'fichier_pdf' => 'bibliotheque/pdfs/ZFEZlrRLDMoQzM56up1yqsnIHigcjEnbksYMfQ4t.pdf',
                'cover_image' => 'bibliotheque/covers/U1vjAXz5GlPYpF2mpHuR2PhYDoO91cUjlxyaHqu5.jpg',
                'nombre_pages' => 265,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Techniques de Secrétariat et Accueil Professionnel',
                'auteur' => 'Martine Tchouameni',
                'description' => 'Organisation administrative, rédaction de courriers officiels, gestion des rendez-vous et accueil physique et téléphonique d\'excellence.',
                'categorie' => 'gestion',
                'fichier_pdf' => 'bibliotheque/pdfs/aLrLLfzC2qpxMSDI6i3zxDxqLVNxRiom2msOVjiR.pdf',
                'cover_image' => 'bibliotheque/covers/U4bVOkqqibpanXMSZomyYLoL2ASojzggkWRZiAdI.jpg',
                'nombre_pages' => 170,
                'points_requis' => 0,
            ],
            [
                'titre' => 'E-commerce et Vente en Ligne : Les Bonnes Pratiques',
                'auteur' => 'Kevin Onana',
                'description' => 'Créer une boutique en ligne rentable, configurer les passerelles de paiement locales (Mobile Money) et gérer les livraisons efficacement.',
                'categorie' => 'commerce',
                'fichier_pdf' => 'bibliotheque/pdfs/d0axNgmrLtEQxKledL8OMtkDrNGiHjtloOPWmzQV.pdf',
                'cover_image' => 'bibliotheque/covers/Us9qmlg4DBKkYLyS5F66juElYfjsZmpjDuoVr90Y.jpg',
                'nombre_pages' => 220,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Prise de Parole en Public et Art Oratoire',
                'auteur' => 'Bernard Muna',
                'description' => 'Vaincre le trac, structurer un discours percutant, maîtriser le langage corporel et captiver son auditoire lors de toute prise de parole.',
                'categorie' => 'developpement_personnel',
                'fichier_pdf' => 'bibliotheque/pdfs/eDEw0eR9AGStqNM6D40D4aaWN2LuBGEyefjAIBQD.pdf',
                'cover_image' => 'bibliotheque/covers/bDpgbFOunyo30dVO8HijsFCb5IWBzIbqPzIehENp.jpg',
                'nombre_pages' => 140,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Maintenance Matérielle et Dépannage Informatique',
                'auteur' => 'Roger Kenfack',
                'description' => 'Diagnostic des pannes matérielles et logicielles, remplacement de composants, installation de systèmes d\'exploitation et optimisation des PC.',
                'categorie' => 'informatique',
                'fichier_pdf' => 'bibliotheque/pdfs/foNKnhNuCLCFuFN7qIlAdPqZJiqERHMwQqJbt1jB.pdf',
                'cover_image' => 'bibliotheque/covers/bvz0yALlVPX2gBRgPua7VPJSbVItbEB6X0KUzqFU.jpg',
                'nombre_pages' => 250,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Fiscalité Pratique des Entreprises et Déclarations',
                'auteur' => 'Cabinet Conseil Fiscal',
                'description' => 'Comprendre les régimes d\'imposition, la TVA, l\'impôt sur les sociétés, et réussir ses déclarations fiscales sans pénalités.',
                'categorie' => 'comptabilite',
                'fichier_pdf' => 'bibliotheque/pdfs/hW734TfYOVjpZ3xhuW8iOIqZYUBC37tdHkexATje.pdf',
                'cover_image' => 'bibliotheque/covers/cKqDS0zRwqnEp1jqLBFyqOpsDEUP1rdN76CruSr2.jpg',
                'nombre_pages' => 215,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Intelligence Artificielle et Outils No-Code au Travail',
                'auteur' => 'Aurélien Vaneck',
                'description' => 'Exploiter l\'IA générative et les outils d\'automatisation pour multiplier par 5 votre productivité au quotidien.',
                'categorie' => 'informatique',
                'fichier_pdf' => 'bibliotheque/pdfs/kBRCpH2e1JRDPaz3ZY9XYhMmY1veIW8hdOTWROGv.pdf',
                'cover_image' => 'bibliotheque/covers/dDgdxS46bX6AX4jwKN20DxgjOYdRbB36NmDFSLQa.jpg',
                'nombre_pages' => 165,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Guide de la Gestion de Stock et Approvisionnement',
                'auteur' => 'Fabrice Ndongo',
                'description' => 'Méthodes de valorisation des stocks (FIFO/LIFO), seuils de réapprovisionnement, inventaires et optimisation des coûts logistiques.',
                'categorie' => 'gestion',
                'fichier_pdf' => 'bibliotheque/pdfs/luNk1mQGsPy0cntygKZpT8uXfMzpoM7ZixKQN0vc.pdf',
                'cover_image' => 'bibliotheque/covers/iYNfdhJgsYj8arGC3R5hM5H0CHIvGVCszvuPwgRE.jpg',
                'nombre_pages' => 195,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Fondamentaux du Droit du Travail et Gestion Sociale',
                'auteur' => 'Me Christine Ngassa',
                'description' => 'Contrat de travail, congés payés, conventions collectives, procédures de licenciement et droits & devoirs des employeurs et salariés.',
                'categorie' => 'droit',
                'fichier_pdf' => 'bibliotheque/pdfs/m7HQ8SXBfSFDkBVLvQuKW3ojEpV33deyHPDR3E1Y.pdf',
                'cover_image' => 'bibliotheque/covers/nrndFYugPCMpQ5UkL8y2mnm4IMp0GlhJwihnnUOz.jpg',
                'nombre_pages' => 240,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Stratégies de Vente B2B et Prospection Téléphonique',
                'auteur' => 'Thierry Bopda',
                'description' => 'Créer des scripts de qualification percutants, traiter les objections clients et conclure des ventes à haute valeur ajoutée.',
                'categorie' => 'commerce',
                'fichier_pdf' => 'bibliotheque/pdfs/odXdxXSN9j5GwmM98xxCgRnpriLCQ7Y0pexuAHuX.pdf',
                'cover_image' => 'bibliotheque/covers/rVKLXzrv4ncdzRDAIjryX16Oox2TykMqmiQN4yPl.jpg',
                'nombre_pages' => 185,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Communication d\'Entreprise & Relations Publiques',
                'auteur' => 'Valérie Simo',
                'description' => 'Gestion de l\'image de marque, relations presse, communication de crise et valorisation des initiatives de l\'entreprise.',
                'categorie' => 'marketing',
                'fichier_pdf' => 'bibliotheque/pdfs/ruFCBxfsvMjBOzrgsEdAQ1lebHQy6Eyd8JaPzkj1.pdf',
                'cover_image' => 'bibliotheque/covers/tBKzn2fwrZBbUYA5DeqixtL7nvLS6apDLD0wnfwp.jpg',
                'nombre_pages' => 200,
                'points_requis' => 0,
            ],
            [
                'titre' => 'Méthodologie de Rédaction de Rapport & Mémoire Professionnel',
                'auteur' => 'Prof. Daniel Nguemo',
                'description' => 'Conseils méthodologiques pour structurer, rédiger et soutenir brillamment un rapport de stage, mémoire de fin d\'études ou projet professionnel.',
                'categorie' => 'developpement_personnel',
                'fichier_pdf' => 'bibliotheque/pdfs/vu0exySqGqCDmKfUy50wUqRLte8Os5dd29sF0lVF.pdf',
                'cover_image' => 'bibliotheque/covers/w9pJnAZO6DSOcMKCjnIXy5OXbUtUdRPe25z5ja98.jpg',
                'nombre_pages' => 155,
                'points_requis' => 0,
            ],
        ];

        $inserted = 0;
        foreach ($books as $book) {
            Bibliotheque::updateOrCreate(
                ['fichier_pdf' => $book['fichier_pdf']],
                array_merge($book, [
                    'active' => true,
                    'vues' => rand(15, 250),
                    'telechargements' => rand(5, 80),
                ])
            );
            $inserted++;
        }

        $this->command->info("BibliothequeSeeder : {$inserted} livres enregistrés avec succès dans la bibliothèque !");
    }
}
